# Generated by Django 3.1.5 on 2021-01-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210113_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Faculty',
            field=models.CharField(choices=[('manager', 'Quản Lý'), ('staff', 'Tư Vấn')], default='Tư Vấn', max_length=20, null=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=190, null=None),
        ),
    ]
